### ISSUE TITLE
Error in /project

### ISSUE THREAD

**Issue by avdata99** [okfn/network#97]
Some URLs do not display the project properly
Example: https://network.okfn.org/project/portal-de-datos-abiertos
We expect an overlay to show

![image](https://github.com/okfn/network/assets/3237309/f332f515-f849-4d02-8e8f-b3f59c8784b2)

Govdirectory project is displayed twice

![image](https://github.com/okfn/network/assets/3237309/575f80ce-9056-4dcf-b34c-3e25cb92dc2c)

**Comment by avdata99** [comment]
Govdirectory is defined twice in the CSV

![image](https://github.com/okfn/network/assets/3237309/efe433a5-445d-4664-9e91-f36142dcb256)

**Comment by sapetti9** [comment]
Thanks @avdata99, I took off one of the entries from the csv.

**Comment by sapetti9** [comment]
Also, the projects from the second section ("Other projects in the open space"), are not feeding the drop down menu (e.g. we have projects from Argentina, but I cannot see Argentina in the drop down menu when I filter the projects by country).

**Comment by avdata99** [comment]
@sapetti9, we are ignoring _outside_ projects for filters.
I pushed a change to fix it. It look it's working now as expected

![image](https://github.com/okfn/network/assets/3237309/e7815f87-79ab-4fb1-8e15-6b4a4d4754ae)

Please feel free to close the issue if we are done or correct me if it's ok to ignore _outside_ projects

**Comment by sapetti9** [comment]
Hi @avdata99, the preview of the project is still throwing an error (e.g. https://network.okfn.org/project/UTOPIX)

<img width="1033" alt="Schermata 2023-06-01 alle 09 53 33" src="https://github.com/okfn/network/assets/74717970/63f86cbb-b7f9-4b86-8895-b1f2eb9cba8b">

**Comment by aivuk** [comment]
@sapetti9 this happens because the column slug from the projects csv must be lowercase. Already fixed

**Comment by aivuk** [comment]
@sapetti9 I also fixed the errors when you accessed directly a link to an external project as https://network.okfn.org/project/theturingway/
